[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts/=D:/Project/blockchain/foundry/governance_dao/lib/openzeppelin-contracts/contracts/",
    "@forge-std/=D:/Project/blockchain/foundry/governance_dao/lib/forge-std/src/",
    "@chainlink/contracts/=D:/Project/blockchain/foundry/governance_dao/lib/chainlink-brownie-contracts/contracts/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
